#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect requirements
# apt-get install nginx
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
echo 'Holberton School' > index.html
mv index.html /var/www/html/
