#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect requirements
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > index.html
sudo mv index.html /var/www/html/
sudo service nginx start
