#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > index.html
sudo mv index.html /var/www/html/
sed -i '/server_name _;/a\\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}\n' /etc/nginx/sites-available/default
sudo service nginx restart
