#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx
text="server_name _;"
replace="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sed -i "/$text/a\\$replace" /etc/nginx/sites-available/default
sudo service nginx restart
