#!/usr/bin/env bash
# 0. Double the number of webservers
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' > index.html
sudo mv index.html /var/www/html/
sudo service nginx start
sudo sed -i "46 a 		add_header X-Served-By $HOSTNAME always;" /etc/nginx/sites-available/default
sudo service nginx restart 
