#!/usr/bin/env bash
#5. Is the host on the network - pings an IP address passed as an argument
ip=$1
if [ "$ip" ]
then
	ping -c5 "$ip"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
