#!/usr/bin/env bash
# Fix issue - change port 8080 to 80, remove ipv6only=on
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo sed -i "s/ipv6only=on//" /etc/nginx/sites-enabled/default
sudo service nginx restart
