#!/usr/bin/env bash
#0. Change your home IP - configures localhost to 127.0.0.2 & facebook 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
