#!/usr/bin/env bash                                                                                                               
# 0. Run software as another user                                                                                                 
if (( $# < 1))                                                                                                                    
then                                                                                                                              
        whoami                                                                                                                    
else
	sudo chsh -s /bin/bash "$1"	
        su - "$1" -c whoami                                                                                                         
fi
